### ISSUE TITLE
Implementation Proposal

### ISSUE THREAD

**Issue by rodfersou** [simplesconsultoria/collective.behavior.automaticrelateditems#1]
## Abstract

Provide a behavior to create related items automatically
## Motivation

Our customer needs to make their workflow more simple, and need to have related items automatically populated
## Proposal & Implementation

The idea of this package is to create a subscriber that do one search in the catalog of each filled Tag of the item.

The results of these searches will be counted, and sorted.  The items that match biggest number of Tags will be selected as related items.

Also will have a controlpanel to select how many items should be filled as related items.
## Deliverables

Automatic fill of related items.
## Participants

Rodrigo Ferreira de Souza @rodfersou
Héctor Velarde @hvelarde

**Comment by hvelarde** [comment]
did you look at https://github.com/collective/collective.portlet.relateditems? they have solved the same problem on a different way (seems better to me).

**Comment by rodfersou** [comment]
for me it looks very complex to start with
